const APP_GROUPS = {
    SYSTEM_APP: "SYSTEM_APP",
    FEEDS: "FEEDS",
    PERSONAL_PROFILE:"PERSONAL_PROFILE",
    CHATBOX:"CHATBOX",
    JOB_POSTING:"JOB_POSTING",
    ORGANIZATION_EDITING:"ORGANIZATION_EDITING"
}

export default APP_GROUPS;

